import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

// Add Free Font Awesome Icons
// https://fontawesome.com/v5.15/icons?d=gallery&p=2&s=solid&m=free
// In order to add an icon, you have to:
// 1) add the icon name in the import statement below;
// 2) add the icon name to the library.add() statement below.
import {
    faArrowAltCircleUp,
    faCog,
    faDatabase,
    faDownload,
    faEdit,
    faExclamationTriangle,
    faFileAlt,
    faPrint,
    faSync,
    faEye,
    faEyeSlash,
    faList,
    faPause,
    faPlay,
    faPlus,
    faSearch,
    faTachometerAlt,
    faTimes,
    faTimesCircle,
    faTrash,
    faCheckCircle,
    faStream,
    faSave,
    faExclamationCircle,
    faBullhorn,
    faArrowsAltV,
    faUnlink,
    faQuestionCircle,
    faImages,
    faUpload,
    faCopy,
    faCheck,
    faFile,
    faAward,
    faLink,
    faChevronDown,
    faSignOutAlt,
    faPen,
    faExternalLinkSquareAlt,
    faSpinner,
    faUndo,
    faPlusCircle,
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faWrench,
    faClock,
    faCalendarAlt,
    faHeartbeat,
    faFilter,
    faInfoCircle,
    faClone,
    faCertificate,
    faFolder,
    faFolderOpen,
} from "@fortawesome/free-solid-svg-icons";

library.add(
    faArrowAltCircleUp,
    faCog,
    faDatabase,
    faDownload,
    faEdit,
    faExclamationTriangle,
    faFileAlt,
    faPrint,
    faSync,
    faEye,
    faEyeSlash,
    faList,
    faPause,
    faPlay,
    faPlus,
    faSearch,
    faTachometerAlt,
    faTimes,
    faTimesCircle,
    faTrash,
    faCheckCircle,
    faStream,
    faSave,
    faExclamationCircle,
    faBullhorn,
    faArrowsAltV,
    faUnlink,
    faQuestionCircle,
    faImages,
    faUpload,
    faCopy,
    faCheck,
    faFile,
    faAward,
    faLink,
    faChevronDown,
    faSignOutAlt,
    faPen,
    faExternalLinkSquareAlt,
    faSpinner,
    faUndo,
    faPlusCircle,
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faLink,
    faWrench,
    faClock,
    faCalendarAlt,
    faHeartbeat,
    faFilter,
    faInfoCircle,
    faClone,
    faCertificate,
    faFolder,
    faFolderOpen,
);

export { FontAwesomeIcon };
